spring.application.name=psicomanager-api
spring.datasource.url=jdbc:mysql://localhost:3310/psicomanager
spring.datasource.username=root
spring.datasource.password=*Root1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-pratform=org.hibernate.dialect.MySQLDialect



security.jwt.token.secret="my-temporary-secret"