ALTER TABLE `sessions_schedule`
    MODIFY COLUMN `STAGE` enum('CONCLUDED','OPENED','CANCELLED','RESCHEDULED','ABSENT') DEFAULT 'OPENED';

ALTER TABLE `sessions_schedule`
    ADD COLUMN `TYPE` enum('PRESENTIAL','REMOTE') NOT NULL DEFAULT 'PRESENTIAL' AFTER `STAGE`;
